/*
 *  TLV_Types.h
 *  TalkToOscar
 *
 *  Created by Alex Nichol on 3/23/11.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */

#define TLV_MULTICONN_FLAGS 74
#define TLV_FEEDBAG_RIGHTS_QUERY_TAGS_FLAGS 11

// OSERVICE_RESPONSE_TAGS
#define TLV_GROUP_ID 13
#define TLV_RECONNECT_HERE 5
#define TLV_LOGIN_COOKIE 6
#define TLV_SSL_CERTNAME 141
#define TLV_SSL_STATE 142

// used in an ICBM message
#define TLV_ICBM__TAGS_IM_DATA 2
#define TLV_ICBM__TAGS_REQUEST_HOST_ACK 3
#define TLV_ICBM__TAGS_AUTO_RESPONSE 4
#define TLV_ICBM__TAGS_STORE 6
#define TLV_ICBM__IM_DATA_TAGS_IM_CAPABILITIES 0x0501
#define TLV_ICBM__IM_DATA_TAGS_IM_TEXT 0x0101

// FEEDBAG_RIGHTS_REPLY
#define TLV_FEEDBAG_RIGHTS_MAX_ITEM_ATTRS 3
#define TLV_FEEDBAG_RIGHTS_MAX_CLIENT_ITEMS 5
#define TLV_FEEDBAG_RIGHTS_MAX_ITEM_NAME_LEN 6
#define TLV_FEEDBAG_RIGHTS_MAX_RECENT_BUDDIES 7
#define TLV_FEEDBAG_RIGHTS_MAX_BUDDIES_PER_GROUP 12
#define TLV_FEEDBAG_RIGHTS_MAX_MEGA_BOTS 13
#define TLV_FEEDBAG_RIGHTS_MAX_SMART_GROUPS 14

#define TLV_BUDDY__RIGHTS_QUERY_TAGS_FLAGS 5

#define TLV_NICK_FLAGS 1
#define TLV_BART_INFO 29

#define TLV_RECENT_BUDDY 106

#define TLV_IDLE_TIME 4

#define TLV_UNAVAILABLE_DATA 4

#define TLV_ERROR_TEXT 27

#define TLV_PD_MODE 202
#define TLV_PD_MASK 203
#define TLV_PD_FLAGS 204
